language: go
services:
- mysql
- postgres
go:
- '1.5'
- '1.6'
- tip
env:
- GO15VENDOREXPERIMENT="1"
install:
- go get github.com/Masterminds/glide
before_script: 
script:
- glide install
- go test -race $(glide novendor)
before_deploy:
- go run internal/scripts/build_release_artifacts.go
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: CKHCervD3zk30TFOumN9l5yThZKumYpu15qoZaV2udsxOS85JIgp0H536Zga8OxGEMhUqFGLnKvsxOuhDlwEoI0yjBDGybXwe8I8Y6Buu1AdYYW7e0g2voCan+mgLsDbT4GsP71DcZ0rWMcfrr447J8lZl1o2BgNKN9t1MKdQGWkNQhp81gv8GCsDIU+uZl+Wnpkivlk1blGXoK7/+E/8xzC+UF+d0t7IrtqLa2sjf1V9OZAWdBfLa4HAhgJ720OkNYwzjsObmokvYbE2nVgTV692kBhi/so6PRqQgxXKwuKG7oGyFZ8KbeiW2ObPWZBpDY+UGh03DChLnkYg9t0NS6XmLQuhtkVuomNWjde/bch+NAM/LJIbME9eFPRJh+ZY9LvkeEcQbOHoiwqH1R24NEANfl9kb7QwEATYa/zGsJ66l16ynJqmvEfpLhB15rt8FgNLurGdt/mtiGmGlh8ZWiBIl1CH3Fs1KGzXFat02DZtQWbjiv53Aw732CLhHI6myrnxzbK2AmINYiwrKNqYY+7H+5f7y8dofupiOFegJM2xdQHHIcxqkfa40Ob914ZNEt3OFSfet65pQIYebqeFuTAP/1CsIYvhh8B56VMwfKpW+tasNcqZJhThxL7v6R76d386REsyCRLl/dPqQncOljIneOaBbWYVPaNWOFWHPM=
deploy:
  provider: releases
  api_key:
    secure: KZe+4gRlHobXf8Q8rzy4rQq0joMtVC3MVU8NxHJCQUXItqzE/+6kMugLoEgUdWgalLtRWBLRyJPKuPYnjcUnoh2AA1EaXgFAtOI5Rd0dJj1R5j0uTNh9zw/v9IY7ZqrR6cZrM8S8lKUIpDgkNROQeBcWk/UUGNXNl/DdjPSTDwVkixaVmmdm3tZ/tE/05PTLMX/qSpa7bGPoIGwFBS4hkr6neaA8jYSfcHKymP09KArgnV7WsO9qIU/aHMvYcxGGls4FdSQXgpMKB24sTPsZXyp2I2PJkZ2aM4FzEWjY8pSqSrY3byp4F1alQIECRCESMAKuBXu22g7BinidYskzaAreM4F09JHSTW163sDfzJk3E6uJabZhnBip9RyDQBRb12uZHJpF7129hgRthopEXsag1TN0NXO9JK/5WDpQhFV9ZK9uHj6Mt9Hi53Wos1sF/w++wU+WSGuQVTzd64uKO8jGnxqfh6PlXnri6RVgBAD40Kik95RNo/tUQ6lUKM259hUJwwwtNmAgHtBStrR3NRDiT3MRQonAKU6a89TWHTMk6kRcNzXCwa/u2TS6hbc/75yPyCXtXyWYpR3r0a+noH7qu3vI5cb8uPzudZYvEgdfyq5HYxjr2aUYAwiwxhz0BdSmLB7sis9qEaQ4ZKFCq199IROuo+L/SLtVqfGrDLI=
  file: dist/*
  file_glob: true
  on:
    repo: stellar/go
    tags: true
    go: '1.6'
